version: "3.9"

services:
  mqtt_broker:
    image: "eclipse-mosquitto:latest"
    container_name: mosquitto
    networks:
      - smartrash-net
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  db_listener:
    build:
      context: ./mqtt-listener
      dockerfile: ./Dockerfile-listener
    container_name: mqtt_listener
    depends_on:
      - mqtt_broker
    # restart: always
    networks:
      - smartrash-net
    # ports:
    # - "8080:8080"
    volumes:
      - .:/usr/app

  postgres:
    image: postgres:15-bullseye
    container_name: sensor_db
    environment:
      POSTGRES_PASSWORD: admin
    restart: always
    networks:
      - smartrash-net
    expose:
      - "5432"

  adminer:
    image: adminer
    restart: always
    networks:
      - smartrash-net
    ports:
      - 8080:8080

networks:
  smartrash-net:
    driver: bridge
